Dev_Duy
webpress-vn/vn-geography pull request #1
Opened 2020-10-05 09:45 UTC by duylive

Init & create migration

2020-10-05 09:48 UTC, duylive commented
Create providers, transfomers, repositories, entity

2020-10-06 02:07 UTC, sonhaichu requested changes

2020-10-06 02:09 UTC, duylive commented on src/database/migrations/2020_10_03_180248_create_cities_table.php
> +            $table->string('local');
Mình nghĩ là local để lưu thông tin theo khu vực,vùng miền ví dụ như Hà Nội ở miền Bắc...

2020-10-06 02:10 UTC, duylive commented on .idea/vn-geography.iml
> +</module>
ok sếp đã ignore

2020-10-06 02:12 UTC, duylive commented on src/database/migrations/2020_10_03_180248_create_cities_table.php
> +            $table->string('status')->default(1);
Mình dựa theo 1 số package khác các table đều có trường này. Về trạng thái của tỉnh thành gồm có những gì thì mình chưa hình dung được vì phạm trù của nó khá rộng. Nếu trường này không thực sự cần thiết thì mình sẽ bỏ

2020-10-06 02:13 UTC, duylive commented on src/app/Entities/Ward.php
> +namespace HaiCS\Laravel\Generator\Entities;
Yes !

2020-10-06 02:14 UTC, duylive commented on src/app/Providers/GeographyServiceProvider.php
> +namespace HaiCS\Laravel\Geography\Providers;
Yes !

2020-10-06 02:14 UTC, duylive commented on src/app/Repositories/CityRepository.php
> +namespace HaiCS\Laravel\Generator\Repositories;
Yes !

2020-10-06 02:14 UTC, duylive commented on src/app/Transformers/DistrictTransformer.php
> +namespace HaiCS\Laravel\Generator\Transformers;
Yes !

2020-10-06 02:14 UTC, duylive commented on src/app/Transformers/WardTransformer.php
> +namespace HaiCS\Laravel\Generator\Transformers;
Yes !

2020-10-06 02:19 UTC, sonhaichu commented on src/database/migrations/2020_10_03_180248_create_cities_table.php
> +            $table->string('status')->default(1);
status active = 1
status pending = 2

2020-10-06 02:21 UTC, sonhaichu commented on src/database/migrations/2020_10_03_180248_create_cities_table.php
> +            $table->string('local');
ok. Vậy từ local chưa đúng nghĩa cho lắm. a đổi nó thành area + cho nó nullable

2020-10-09 02:00 UTC, sonhaichu commented on src/routes/web.php
> +    Route::get('/provinces/{slug}/districts/{slug}/wards/{slug}', 'VCComponent\Laravel\Geography\Contracts\ViewWardDetailControllerInterface@show');
- Mình đang viết api nên sẽ viết router vào file routes/api.php
- Sử dụng cách định nghĩa api giống như hướng dẫn của package dingo/api

- Thiếu các router thêm, sửa, xóa
- Router nên chia theo các resource (ở đây có 3 resource là provinces, districts và wards)

2020-10-09 02:04 UTC, duylive commented on src/routes/web.php
> +    Route::get('/provinces/{slug}/districts/{slug}/wards/{slug}', 'VCComponent\Laravel\Geography\Contracts\ViewWardDetailControllerInterface@show');
ok sếp

2020-10-09 02:05 UTC, duylive commented on composer.json
> +    "name": "duylive/laravel-package-geography",
ok sếp

2020-10-09 02:07 UTC, duylive commented on src/app/Entities/District.php
> +    public function city()
yes

2020-10-16 04:44 UTC, merged